### ISSUE TITLE
Window has incorrect size when using wayland

### ISSUE THREAD

**Issue by remimimimimi** [LordMZTE/snek#1]
![image](https://i.ibb.co/cL6rdJv/screenshot-2020-10-13-20-02-21-652869517.png)
Please fix this, @LordMZTE.

**Comment by remimimimimi** [comment]
When i change window mode into float food appear again.
I use sway(wayland).

**Comment by remimimimimi** [comment]
![image2](https://i.ibb.co/tMkv47Q/screenshot-2020-10-13-20-10-48-131980355.png)

**Comment by LordMZTE** [comment]
i can't reproduce this, as ive never used wayland. the blue part should not ever be visible, as the window isn't resizable, and the top is cut off too. i have no idea what the problem could be

**Comment by LordMZTE** [comment]
it looks like wayland is letting you resize the window even tho its not supposed to be possible. the areas outside the game board should also be blue, so this looks like it is not a bug. please reopen if you have any more issues regarding this
